import type { ActivityItem, ActivityType } from "@/lib/demo-data/types"

export const activityItems: ActivityItem[] = [
  {
    id: "act-001",
    clientId: "northstar-bank",
    modelId: "cash-velocity-v32",
    type: "stress-test-failed",
    title: "Holiday stress test failed",
    detail: "Below-the-line holiday stress produced alert inflation well above the current analyst capacity threshold.",
    actor: "Validation Analytics",
    occurredAt: "45 minutes ago",
    category: "Testing",
  },
  {
    id: "act-002",
    clientId: "northstar-bank",
    modelId: "wire-escalation-v21",
    type: "report-generated",
    title: "OCC-aligned brief generated",
    detail: "Executive summary and testing appendix were assembled for steering-committee review.",
    actor: "Reporting Portal",
    occurredAt: "2 hours ago",
    category: "Reporting",
  },
  {
    id: "act-003",
    clientId: "northstar-bank",
    modelId: "cash-velocity-v32",
    type: "remediation-overdue",
    title: "Commercial threshold remediation overdue",
    detail: "Segmented threshold proposal missed the agreed governance checkpoint and now requires escalation.",
    actor: "Governance PMO",
    occurredAt: "3 hours ago",
    category: "Finding",
  },
  {
    id: "act-004",
    clientId: "northstar-bank",
    modelId: "wire-escalation-v21",
    type: "approval-completed",
    title: "Audit pack approval completed",
    detail: "Partner quality review cleared the draft audit appendix with no material edits remaining.",
    actor: "A. Patel",
    occurredAt: "Yesterday",
    category: "Reporting",
  },
  {
    id: "act-005",
    clientId: "northstar-bank",
    modelId: "cash-velocity-v32",
    type: "revalidation-triggered",
    title: "Revalidation trigger opened",
    detail: "Holiday-volume drift and remediation slippage triggered an accelerated retest requirement.",
    actor: "Compliance Oversight",
    occurredAt: "Yesterday",
    category: "Governance",
  },
  {
    id: "act-006",
    clientId: "northstar-bank",
    modelId: "cash-velocity-v32",
    type: "audit-note-added",
    title: "Audit note added to evidence index",
    detail: "Analyst replay assumptions were annotated for future regulator walkthroughs and audit playback.",
    actor: "Internal Audit Liaison",
    occurredAt: "2 days ago",
    category: "Governance",
  },
  {
    id: "act-007",
    clientId: "harbor-credit",
    modelId: "customer-risk-v5",
    type: "benchmark-variance-detected",
    title: "Benchmark variance detected",
    detail: "Challenger scorecard benchmark diverged in the private-client segment beyond approved tolerance.",
    actor: "Model Risk Advisory",
    occurredAt: "1 hour ago",
    category: "Finding",
  },
  {
    id: "act-008",
    clientId: "harbor-credit",
    modelId: "customer-risk-v5",
    type: "severe-finding-created",
    title: "Severe methodology finding created",
    detail: "High-net-worth uplift rationale was escalated for written governance support and segment evidence.",
    actor: "Validation Lead",
    occurredAt: "4 hours ago",
    category: "Finding",
  },
  {
    id: "act-009",
    clientId: "harbor-credit",
    modelId: "customer-risk-v5",
    type: "document-requested",
    title: "Supporting design memo requested",
    detail: "Model owner was asked to provide design rationale and governance linkage for uplift logic.",
    actor: "Quality Review",
    occurredAt: "Yesterday",
    category: "Governance",
  },
  {
    id: "act-010",
    clientId: "harbor-credit",
    modelId: "customer-risk-v5",
    type: "milestone-due",
    title: "Management response milestone due",
    detail: "Responses and due dates need confirmation before the committee deck is finalized.",
    actor: "Engagement Manager",
    occurredAt: "Yesterday",
    category: "Governance",
  },
  {
    id: "act-011",
    clientId: "harbor-credit",
    modelId: "customer-risk-v5",
    type: "action-assigned",
    title: "Owner action assigned",
    detail: "Documentation uplift and challenger rationale traceability were assigned to the model owner.",
    actor: "Validation PMO",
    occurredAt: "2 days ago",
    category: "Finding",
  },
  {
    id: "act-012",
    clientId: "harbor-credit",
    modelId: "customer-risk-v5",
    type: "governance-comment-added",
    title: "Governance comment added",
    detail: "Committee sponsor requested clearer articulation of conceptual soundness decisions in the final pack.",
    actor: "Robert Chen",
    occurredAt: "2 days ago",
    category: "Governance",
  },
  {
    id: "act-013",
    clientId: "summit-payments",
    modelId: "sanctions-screening-v14",
    type: "external-data-source-failed",
    title: "External sanctions source failed",
    detail: "Upstream disposition timestamp feed was unavailable during scoping extract reconciliation.",
    actor: "Data QA Pod",
    occurredAt: "30 minutes ago",
    category: "Testing",
  },
  {
    id: "act-014",
    clientId: "summit-payments",
    modelId: "sanctions-screening-v14",
    type: "data-quality-issue-detected",
    title: "Data-quality issue detected",
    detail: "Disposition timestamps are still excluded from the initial extract and block end-to-end analyst replay.",
    actor: "Validation Analytics",
    occurredAt: "2 hours ago",
    category: "Testing",
  },
  {
    id: "act-015",
    clientId: "summit-payments",
    modelId: "sanctions-screening-v14",
    type: "evidence-missing",
    title: "Evidence gap flagged",
    detail: "Current scoping packet lacks analyst-case evidence needed for a regulator-ready testing narrative.",
    actor: "Evidence Control",
    occurredAt: "Yesterday",
    category: "Reporting",
  },
  {
    id: "act-016",
    clientId: "summit-payments",
    modelId: "sanctions-screening-v14",
    type: "test-run-completed",
    title: "Scoping replay run completed",
    detail: "Initial sanctions replay produced expected screening output with known data omissions carried forward.",
    actor: "Scenario Specialists",
    occurredAt: "Yesterday",
    category: "Testing",
  },
  {
    id: "act-017",
    clientId: "summit-payments",
    modelId: "sanctions-screening-v14",
    type: "calibration-changed",
    title: "Calibration setting changed",
    detail: "Initial fuzzy threshold and enrichment assumptions were adjusted for the phase-2 testing plan.",
    actor: "Scenario Specialists",
    occurredAt: "2 days ago",
    category: "Testing",
  },
  {
    id: "act-018",
    clientId: "atlas-private-bank",
    modelId: "watchlist-fuzzy-match-v9",
    type: "adversarial-scenario-flagged",
    title: "Adversarial scenario flagged",
    detail: "Transliteration edge cases produced unstable match outcomes across repeated test runs.",
    actor: "Model Risk Advisory",
    occurredAt: "35 minutes ago",
    category: "Testing",
  },
  {
    id: "act-019",
    clientId: "atlas-private-bank",
    modelId: "watchlist-fuzzy-match-v9",
    type: "severe-finding-created",
    title: "Severe fuzzy-match finding created",
    detail: "Repeatability issues were elevated to a critical finding ahead of the risk committee packet.",
    actor: "Validation Lead",
    occurredAt: "1 hour ago",
    category: "Finding",
  },
  {
    id: "act-020",
    clientId: "atlas-private-bank",
    modelId: "private-client-monitor-v27",
    type: "approval-completed",
    title: "Client readout approval completed",
    detail: "Steering committee package for the private-client monitor was approved for distribution.",
    actor: "S. Ibrahim",
    occurredAt: "Yesterday",
    category: "Reporting",
  },
  {
    id: "act-021",
    clientId: "atlas-private-bank",
    modelId: "watchlist-fuzzy-match-v9",
    type: "audit-note-added",
    title: "Evidence retention note added",
    detail: "Audit liaison captured the reproducibility caveat and required retest documentation standards.",
    actor: "Audit Liaison",
    occurredAt: "Yesterday",
    category: "Governance",
  },
  {
    id: "act-022",
    clientId: "atlas-private-bank",
    modelId: "watchlist-fuzzy-match-v9",
    type: "support-issue-created",
    title: "Support issue created",
    detail: "Demo support ticket opened for evidence attachment persistence in retest runs.",
    actor: "Platform Admin",
    occurredAt: "2 days ago",
    category: "Governance",
  },
  {
    id: "act-023",
    clientId: "atlas-private-bank",
    type: "persona-changed",
    title: "Persona changed to validation lead",
    detail: "Leadership walkthrough switched into validation-lead mode for the evidence and testing review sequence.",
    actor: "Platform Admin",
    occurredAt: "2 days ago",
    category: "Governance",
  },
  {
    id: "act-024",
    clientId: "atlas-private-bank",
    type: "client-switched",
    title: "Client context switched",
    detail: "Demo moved from Northstar Bank into Atlas Private Bank for committee-readout comparison.",
    actor: "Platform Admin",
    occurredAt: "2 days ago",
    category: "Governance",
  },
  {
    id: "act-025",
    clientId: "atlas-private-bank",
    type: "configuration-updated",
    title: "Configuration updated",
    detail: "Persona-driven dashboard composition and CTA routing were refreshed for the stakeholder demo.",
    actor: "Platform Admin",
    occurredAt: "3 days ago",
    category: "Governance",
  },
  {
    id: "act-026",
    clientId: "northstar-bank",
    type: "demo-health-warning",
    title: "Demo health warning",
    detail: "A transient build cache mismatch was detected and auto-resolved before the leadership walkthrough.",
    actor: "Demo Monitor",
    occurredAt: "3 days ago",
    category: "Governance",
  },
  {
    id: "act-027",
    clientId: "northstar-bank",
    modelId: "gai-001-alert-narrative-assistant",
    type: "report-generated",
    title: "GenAI workflow validation brief generated",
    detail: "Draft GenAI workflow validation section was assembled with grounding, safety, and human-review controls.",
    actor: "Reporting Portal",
    occurredAt: "40 minutes ago",
    category: "Reporting",
  },
  {
    id: "act-028",
    clientId: "northstar-bank",
    modelId: "gai-001-alert-narrative-assistant",
    type: "adversarial-scenario-flagged",
    title: "Prompt-injection scenario flagged",
    detail: "Instruction-conflict testing still produced weak recommendation-boundary language in selected replays.",
    actor: "AI Validation Pod",
    occurredAt: "2 hours ago",
    category: "Testing",
  },
  {
    id: "act-029",
    clientId: "harbor-credit",
    modelId: "gai-002-case-summarization-assistant",
    type: "approval-completed",
    title: "Human-review control walkthrough completed",
    detail: "Reviewer override logging and chronology-grounding controls were accepted for the current pilot narrative.",
    actor: "Controls Advisory",
    occurredAt: "5 hours ago",
    category: "Governance",
  },
  {
    id: "act-030",
    clientId: "summit-payments",
    modelId: "gai-003-policy-copilot",
    type: "revalidation-triggered",
    title: "Policy freshness revalidation triggered",
    detail: "Stale-guidance testing opened a revalidation trigger after the latest procedure repository lag was confirmed.",
    actor: "Compliance Oversight",
    occurredAt: "1 hour ago",
    category: "Governance",
  },
  {
    id: "act-031",
    clientId: "summit-payments",
    modelId: "gai-003-policy-copilot",
    type: "governance-comment-added",
    title: "Governance comment added on stale guidance",
    detail: "Steering sponsor requested a stronger deployment recommendation tied to source-freshness controls.",
    actor: "Eva Sinclair",
    occurredAt: "Yesterday",
    category: "Governance",
  },
  {
    id: "act-032",
    clientId: "atlas-private-bank",
    modelId: "gai-004-disposition-recommendation-assistant",
    type: "support-issue-created",
    title: "Redaction control issue created",
    detail: "Support ticket opened to track the sensitive-data masking gap identified in adversarial testing.",
    actor: "Platform Admin",
    occurredAt: "55 minutes ago",
    category: "Governance",
  },
  {
    id: "act-033",
    clientId: "atlas-private-bank",
    modelId: "gai-004-disposition-recommendation-assistant",
    type: "severe-finding-created",
    title: "Unsafe recommendation finding created",
    detail: "Disposition recommendation assistant was escalated after unsafe closure language persisted in negative tests.",
    actor: "Validation Lead",
    occurredAt: "90 minutes ago",
    category: "Finding",
  },
]

export function getRecentActivity(clientId?: string): ActivityItem[] {
  if (!clientId) {
    return activityItems
  }

  return activityItems.filter((activity) => activity.clientId === clientId)
}

export function getActivityByType(activity: ActivityItem[], types: ActivityType[]): ActivityItem[] {
  return activity.filter((item) => types.includes(item.type))
}
